import { MediaItem } from '../types/media';

export const FALLBACK_TRENDING_MOVIES: MediaItem[] = [
  {
    id: 1022789,
    tmdbId: 1022789,
    title: 'Inside Out 2',
    overview: 'Teenager Riley\'s mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust aren\'t sure how to feel when Anxiety shows up.',
    posterPath: 'https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/xg27NrXi7EgQxLQVI3PllY9Ro2d.jpg',
    releaseDate: '2024-06-11',
    voteAverage: 7.6,
    voteCount: 4800,
    mediaType: 'movie',
    runtime: 96,
    genres: [{ id: 16, name: 'Animation' }, { id: 10751, name: 'Family' }, { id: 12, name: 'Adventure' }, { id: 35, name: 'Comedy' }]
  },
  {
    id: 533535,
    tmdbId: 533535,
    title: 'Deadpool & Wolverine',
    overview: 'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again.',
    posterPath: 'https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/yDHYTfaA9g37uN3914aX2ftuU20.jpg',
    releaseDate: '2024-07-24',
    voteAverage: 7.7,
    voteCount: 5200,
    mediaType: 'movie',
    runtime: 128,
    genres: [{ id: 28, name: 'Action' }, { id: 35, name: 'Comedy' }, { id: 878, name: 'Science Fiction' }]
  },
  {
    id: 693134,
    tmdbId: 693134,
    title: 'Dune: Part Two',
    overview: 'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family.',
    posterPath: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/xOMo8BRK7PfcJv9JCnx7s520QIe.jpg',
    releaseDate: '2024-02-27',
    voteAverage: 8.2,
    voteCount: 5600,
    mediaType: 'movie',
    runtime: 166,
    genres: [{ id: 878, name: 'Science Fiction' }, { id: 12, name: 'Adventure' }]
  },
  {
    id: 912649,
    tmdbId: 912649,
    title: 'Venom: The Last Dance',
    overview: 'Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie\'s last dance.',
    posterPath: 'https://image.tmdb.org/t/p/w500/aosm8Vh9il46NXIGmD2khRIJvTe.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/3V4kSt3k2y9wJ5p5Feqg2hZz2I7.jpg',
    releaseDate: '2024-10-22',
    voteAverage: 6.8,
    voteCount: 2200,
    mediaType: 'movie',
    runtime: 109,
    genres: [{ id: 28, name: 'Action' }, { id: 878, name: 'Sci-Fi' }, { id: 12, name: 'Adventure' }]
  },
  {
    id: 1184918,
    tmdbId: 1184918,
    title: 'The Wild Robot',
    overview: 'After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island\'s animals and cares for an orphaned baby goose.',
    posterPath: 'https://image.tmdb.org/t/p/w500/wTnV3PCVW5O92JMrvgZ05J37Vby.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/mQZJoIhTEkNhCY22oT5XlTV513b.jpg',
    releaseDate: '2024-09-12',
    voteAverage: 8.4,
    voteCount: 3400,
    mediaType: 'movie',
    runtime: 102,
    genres: [{ id: 16, name: 'Animation' }, { id: 878, name: 'Science Fiction' }, { id: 10751, name: 'Family' }]
  },
  {
    id: 939243,
    tmdbId: 939243,
    title: 'Sonic the Hedgehog 3',
    overview: 'Sonic, Knuckles, and Tails reunite against a powerful new adversary, Shadow, a mysterious villain with powers unlike anything they have faced before.',
    posterPath: 'https://image.tmdb.org/t/p/w500/d8Ryb8AunYAuycVKDp5H9W6oKp4.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/zOpe0eHax92m2zMAgyvdnkYnRUM.jpg',
    releaseDate: '2024-12-19',
    voteAverage: 7.8,
    voteCount: 1900,
    mediaType: 'movie',
    runtime: 110,
    genres: [{ id: 28, name: 'Action' }, { id: 12, name: 'Adventure' }, { id: 35, name: 'Comedy' }, { id: 10751, name: 'Family' }]
  },
  {
    id: 823464,
    tmdbId: 823464,
    title: 'Godzilla x Kong: The New Empire',
    overview: 'Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.',
    posterPath: 'https://image.tmdb.org/t/p/w500/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/qrGtVFsvRw7krTw75SpIE4xEj5P.jpg',
    releaseDate: '2024-03-27',
    voteAverage: 7.2,
    voteCount: 3600,
    mediaType: 'movie',
    runtime: 115,
    genres: [{ id: 28, name: 'Action' }, { id: 878, name: 'Science Fiction' }, { id: 12, name: 'Adventure' }]
  },
  {
    id: 573435,
    tmdbId: 573435,
    title: 'Bad Boys: Ride or Die',
    overview: 'After their late former Captain is framed, Lowrey and Burnett try to clear his name, only to end up on the run themselves.',
    posterPath: 'https://image.tmdb.org/t/p/w500/nP6RliHjxsz4irTKsxe8FRhKZYl.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/ga4OLm4qLxO1ymUpjI668jKkWyW.jpg',
    releaseDate: '2024-06-05',
    voteAverage: 7.5,
    voteCount: 2400,
    mediaType: 'movie',
    runtime: 115,
    genres: [{ id: 28, name: 'Action' }, { id: 35, name: 'Comedy' }, { id: 80, name: 'Crime' }]
  }
];

export const FALLBACK_TRENDING_SERIES: MediaItem[] = [
  {
    id: 94605,
    tmdbId: 94605,
    title: 'Arcane',
    overview: 'Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and incompatible convictions.',
    posterPath: 'https://image.tmdb.org/t/p/w500/abf8tHznhSvl9BAElD2cQY96l11.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/is9ZsfV417K2K4uEa9Y8h9h8v3P.jpg',
    firstAirDate: '2021-11-06',
    voteAverage: 8.8,
    voteCount: 4200,
    mediaType: 'tv',
    numberOfSeasons: 2,
    genres: [{ id: 16, name: 'Animation' }, { id: 10765, name: 'Sci-Fi & Fantasy' }, { id: 10759, name: 'Action & Adventure' }]
  },
  {
    id: 1399,
    tmdbId: 1399,
    title: 'Game of Thrones',
    overview: 'Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war.',
    posterPath: 'https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/2OMB0ynKlyIen9SuJs0qQgu4G8i.jpg',
    firstAirDate: '2011-04-17',
    voteAverage: 8.4,
    voteCount: 23000,
    mediaType: 'tv',
    numberOfSeasons: 8,
    genres: [{ id: 10765, name: 'Sci-Fi & Fantasy' }, { id: 18, name: 'Drama' }, { id: 10759, name: 'Action & Adventure' }]
  },
  {
    id: 100088,
    tmdbId: 100088,
    title: 'The Last of Us',
    overview: '20 years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone.',
    posterPath: 'https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2V7JMrne.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg',
    firstAirDate: '2023-01-15',
    voteAverage: 8.6,
    voteCount: 5100,
    mediaType: 'tv',
    numberOfSeasons: 2,
    genres: [{ id: 18, name: 'Drama' }, { id: 10765, name: 'Sci-Fi & Fantasy' }]
  },
  {
    id: 93405,
    tmdbId: 93405,
    title: 'Squid Game',
    overview: 'Hundreds of cash-strapped players accept a strange invitation to compete in children\'s games. Inside, a tempting prize awaits with deadly high stakes.',
    posterPath: 'https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/2meX1nMdScFOoV4370rqHWKmX0C.jpg',
    firstAirDate: '2021-09-17',
    voteAverage: 7.8,
    voteCount: 14000,
    mediaType: 'tv',
    numberOfSeasons: 2,
    genres: [{ id: 10759, name: 'Action & Adventure' }, { id: 9648, name: 'Mystery' }, { id: 18, name: 'Drama' }]
  },
  {
    id: 76479,
    tmdbId: 76479,
    title: 'The Boys',
    overview: 'A fun and irreverent take on what happens when superheroes—who are as popular as celebrities, as influential as politicians, and as revered as gods—abuse their superpowers rather than use them for good.',
    posterPath: 'https://image.tmdb.org/t/p/w500/2zmTngn1tYC1AvfnNDaRBne8uqD.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg',
    firstAirDate: '2019-07-25',
    voteAverage: 8.5,
    voteCount: 9800,
    mediaType: 'tv',
    numberOfSeasons: 4,
    genres: [{ id: 10765, name: 'Sci-Fi & Fantasy' }, { id: 10759, name: 'Action & Adventure' }]
  },
  {
    id: 66732,
    tmdbId: 66732,
    title: 'Stranger Things',
    overview: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.',
    posterPath: 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
    firstAirDate: '2016-07-15',
    voteAverage: 8.6,
    voteCount: 17000,
    mediaType: 'tv',
    numberOfSeasons: 4,
    genres: [{ id: 18, name: 'Drama' }, { id: 10765, name: 'Sci-Fi & Fantasy' }, { id: 9648, name: 'Mystery' }]
  },
  {
    id: 119051,
    tmdbId: 119051,
    title: 'Wednesday',
    overview: 'A sleuthing, supernaturally infused mystery charting Wednesday Addams\' years as a student at Nevermore Academy.',
    posterPath: 'https://image.tmdb.org/t/p/w500/9PFonQ921WvxTM0ZaeD4qpcuNmO.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/iHSwvFe7FdImpq796bQvtQQuaZc.jpg',
    firstAirDate: '2022-11-23',
    voteAverage: 8.4,
    voteCount: 8200,
    mediaType: 'tv',
    numberOfSeasons: 2,
    genres: [{ id: 10765, name: 'Sci-Fi & Fantasy' }, { id: 9648, name: 'Mystery' }, { id: 35, name: 'Comedy' }]
  },
  {
    id: 106379,
    tmdbId: 106379,
    title: 'Fallout',
    overview: 'The story of haves and have-nots in a world in which there’s almost nothing left to have. 200 years after the apocalypse, the gentle denizens of luxury fallout shelters are forced to return to the irradiated hellscape their ancestors left behind.',
    posterPath: 'https://image.tmdb.org/t/p/w500/AnsZuLpGntqBsqZfcfjZg3Vp5lX.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/2rmK7mnchw9Xr3XdiTFSxTTFqqU.jpg',
    firstAirDate: '2024-04-10',
    voteAverage: 8.3,
    voteCount: 2200,
    mediaType: 'tv',
    numberOfSeasons: 1,
    genres: [{ id: 10765, name: 'Sci-Fi & Fantasy' }, { id: 10759, name: 'Action & Adventure' }, { id: 18, name: 'Drama' }]
  }
];
